language: node_js
node_js:
  - 16
services:
  - docker
before_install:
  - docker-compose -f docker-compose-build.yaml build --parallel
  # Do similar for other three images
script:
  # Tagging
  - docker tag udagram-api-feed ntpac/udagram-api-feed:v3
  - docker tag udagram-frontend:local ntpac/udagram-frontend:v3
  - docker tag udagram-api-user ntpac/udagram-api-user:v3
  - docker tag reverseproxy ntpac/reverseproxy:v3
  # Do similar for other three images
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ntpac/udagram-api-feed:v3
  - docker push ntpac/udagram-frontend:v3
  - docker push ntpac/udagram-api-user:v3
  - docker push ntpac/reverseproxy:v3